stages:
  - compile
  # Don't run the combine stage in pull requests, because deploy is disabled there.
  - name: combine
    if: type != pull_request

jobs:
  include:
  - stage: compile
    os: linux
    language: nix
    nix: 2.3.6
    before_install:
      - git lfs pull
      - echo "trusted-users = root travis" | sudo tee -a /etc/nix/nix.conf && sudo pkill nix-daemon
    install:
      - nix-env -iA cachix -f https://cachix.org/api/v1/install
    script:
      - cachix use urbit2
      - ./sh/cachix
      - make build
      - make release
      - sh/ci-tests

  - stage: compile
    os: linux
    language: generic
    env: STACK_YAML=pkg/hs/stack.yaml
    cache:
      directories:
      - $HOME/.ghc
      - $HOME/.cabal
      - $HOME/.stack
      - $TRAVIS_BUILD_DIR/.stack-work
    before_install:
      - sh/travis-install-stack
    install:
      - stack --no-terminal --install-ghc build urbit-king --only-dependencies
    script:
      - stack test
      - sh/release-king-linux64-dynamic

  - stage: compile
    os: osx
    language: generic
    sudo: required
    env: STACK_YAML=pkg/hs/stack.yaml
    cache:
      directories:
      - $HOME/.ghc
      - $HOME/.cabal
      - $HOME/.stack
      - $TRAVIS_BUILD_DIR/.stack-work
    before_install:
      - sh/travis-install-stack
    install:
      - stack --no-terminal --install-ghc build urbit-king --only-dependencies
    script:
      - stack test
      - sh/release-king-darwin-dynamic

  - stage: combine
    os: linux
    language: generic
    script:
      - sh/combine-release-builds

deploy:
  - skip_cleanup: true
    provider: gcs
    access_key_id: GOOGTADOPP55X5ZTH3IKAXQW
    secret_access_key:
      secure: rSPif0VHX3Q3QpWM9iUt/Z9sicCY8ABuwVFPeT3YUnAAmSXM46PIHKieoGs79kx9IelFyQsM8xS0XWyt4S/haR7VaTJY+zHJjf0AnA1sr5ZIV70t3K0SXzq4+E1ffOZRiC0VmHatPz10wjaIpHxpjcROqQV4M1dBCq2H/rpccIE=
    bucket: bootstrap.urbit.org
    local-dir: release/
    acl: public-read
    on:
      condition: "-d release/"
      repo: urbit/urbit
      all_branches: true
