name: merge
on:
  push:
    branches:
      - 'master'
jobs:
  merge-to-next-js:
    runs-on: ubuntu-latest
    name: "Merge master to release/next-js"
    steps:
      - uses: actions/checkout@v2
      - uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: release/next-js
          github_token: ${{ secrets.JANEWAY_BOT_TOKEN }}

